hive:
  driver: hive
  host: localhost
  port: 10000
  auth: NONE

log:
  level: info
  output: logs/app_log.%Y-%m-%d.log #logs/access_log-%Y-%m-%d-%H-%M-%S.log
  map:
    time: "@timestamp"
    msg: message